if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
  return()
endif()

find_package(GCCAr REQUIRED)
set(CMAKE_AR "${GCCAR_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(GCCNm REQUIRED)
set(CMAKE_NM "${GCCNM_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(GCCRanLib REQUIRED)
set(CMAKE_RANLIB "${GCCRANLIB_EXECUTABLE}" CACHE FILEPATH "" FORCE)
