find_package(LLVMAr REQUIRED)
set(CMAKE_AR "${LLVMAR_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(LLVMNm REQUIRED)
set(CMAKE_NM "${LLVMNM_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(LLVMObjCopy)
if(LLVMObjCopy_FOUND)
  set(CMAKE_OBJCOPY "${LLVMOBJCOPY_EXECUTABLE}" CACHE FILEPATH "" FORCE)
endif()

find_package(LLVMObjDump REQUIRED)
set(CMAKE_OBJDUMP "${LLVMOBJDUMP_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(LLVMRanLib REQUIRED)
set(CMAKE_RANLIB "${LLVMRANLIB_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(LLVMLLD REQUIRED)
set(CMAKE_LINKER "${LLVMLLD_EXECUTABLE}" CACHE FILEPATH "" FORCE)
