name: Validate source/target branches of Pull Request

on:
  pull_request_target:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch/Checkout RawSpeed git repo
        timeout-minutes: 1
        uses: actions/checkout@v4
        with:
          path: 'rawspeed'
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - if: github.event_name == 'pull_request_target' && github.base_ref != 'develop'
        name: Close Pull
        timeout-minutes: 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rawspeed
          gh pr close --comment "Pull Requests should only be submitted to `develop` branch" ${{ github.event.number }}
          exit 1
      - if: github.event_name == 'pull_request_target' && github.head_ref == github.base_ref
        name: Close Pull
        timeout-minutes: 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rawspeed
          gh pr close --comment "Pull Requests source branch should be branched off of the Pull Request's target branch" ${{ github.event.number }}
          exit 1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Trigger the rest of the CI
        timeout-minutes: 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rawspeed
          git fetch origin refs/pull/${{ github.event.number }}/merge:refs/remotes/pull/${{ github.event.number }}/merge
          gh workflow run CI.yml --ref refs/remotes/pull/${{ github.event.number }}/merge
